root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ."
  bin = "./tmp/main -c config.toml"
  delay = 1000
  exclude_dir = ["tmp", "vendor", "testdata", "recipes"]
  include_ext = ["go", "tpl", "tmpl", "html", "css"]
  include_file = ["config.toml"]
  exclude_regex = ["_test\\.go"]

[log]
  time = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
