root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build --tags fts5 -o ./tmp/main ."
  bin = "./tmp/main $(pwd)/recipes"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "recipes"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_regex = ["_test\\.go"]

[log]
  time = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
