[Server]
Address = ":8080"
RecipesPath = "recipes" # Where recipe markdown files will be saved. RecipesPath path must be a
# directory that exists, if it doesn't exist or is deleted after the program starts, recipe changes
# will not be monitored.
SessionSecrets = [ "generate this key with `./cookbook -k`"]
CSRFKey = "generate this key with `./cookbook -k`, make sure it is different than SessionSecrets"
Language = "en" # language to use for fulltext search, see other options here:
# https://github.com/blevesearch/bleve/tree/b7b67d3938fb525d7face7e02d9d18029910f6af/analysis/lang
SecureCookies = true # try to keep true (requires https)
# LLM = "Google" # LLM to use, options are "Google", "Ollama", "OpenAI"

# Depending on the LLM you choose, you may need to configure the following sections.
# [Google]
# APIKey = "get this key from https://aistudio.google.com/app/apikey"
# Model = "gemini-2.0-flash-001" # tested with this model

# [Ollama]
# ServerURL = ""
# Model = ""

# [OpenAI]
# Token = ""
# BaseURL = ""
# Model = ""

# Optionally configure OIDC, FormBasedAuthUsers, or leave both commented out.
# [OIDC]
# Issuer = "https://auth.example.com/application/o/cookbook/"
# EndSessionEndpoint = "https://auth.example.com/application/o/cookbook/end-session/"
# ClientID = "get this id from your oicd provider"
# ClientSecret = "get this id from your oicd provider"
# RedirectURI = "https://127.0.0.1:8081/auth/oidc/callback"
# GroupsClaim = ["optionally add required groups, omit line if no groups required", "cookbook-editor"]

# [FormBasedAuthUsers]
# "username" = "encrypt your password with `./cookbook -p` and put it here"
