version: '3.8'

services:
  hallertau:
    build: .
    restart: unless-stopped
    volumes:
      - ./hallertau.toml:/hallertau/hallertau.toml:ro
      - ./recipes:/hallertau/recipes:rw
      - /etc/ssl/certs:/etc/ssl/certs:ro
    ports:
      - "127.0.0.1:7004:8080"
